serendie/serendie

- .github/workflows/build-tokens.yml
- .github/workflows/publish-code-connect.yml
- .github/workflows/release-package.yml
- .github/workflows/sync-tokens-to-figma.yml
- .npmrc.example
- .npmrc.pages
- design-tokens/package.json
- package-lock.json
- package.json
- style-dictionary-formatter/package.json
- ui/package.json
パッケージをインストールする際の障壁をなるべく少なくしたいため、Package RegistryをGitHubからNPMのPublic Registoryに移行します。
主にGitHub Packages向けの認証情報や設定しました。
GitHub Actionsの設定変更から取り掛かったところ、レジストリを跨いで依存関係がうまく解決できなかったので手動で先行してnpmに公開しました。
> Package RegistryをGitHubからNPMに移行

- ui/src/components/TextArea.tsx
- ui/src/components/TextField.tsx
ref: https://github.com/serendie/internal/issues/474
TextFieldやTextAreaにて、ラベルを指定しない際に上部にgapが生じ、デザイン実装の際に影響を及ぼす問題を修正
> Hide the entire label element when there is no label

- ui/src/components/DropdownMenu.stories.tsx
- ui/src/components/DropdownMenu.tsx
ref: https://github.com/serendie/internal/issues/462
DropdownMenuのpropsにisIconMenuが指定されている際に、表示されるiconをpropsにて変更できるように修正。
> Add an icon property to DropdownMenu component

- ui/src/components/Search.stories.tsx
- ui/src/components/Search.tsx
ref: https://github.com/serendie/internal/issues/475
Search コンポーネントにおいて、width: 100%などの幅指定ができない問題に対処するために、TextFieldやTextAreaなどに行った改善を行いました。
> Improve Search component styling and consolidate CSS class names

- ui/src/components/TextArea.tsx
- ui/src/components/TextField.tsx
ref: https://github.com/serendie/internal/issues/452
TextFieldやTextAreaコンポーネントにおいて、label要素にtextarea/input要素が紐づいていないために、テスト等を行い辛い問題を解決するため、
propsにidが指定されている場合には、id/htmlForにidの値を入れ、idがない場合にはuseIdを用いたid振り出しを行うように実装を行いました。
> Align label and input/textarea id in TextField and TextArea components

- ui/src/components/DropdownMenu.stories.tsx
- ui/src/components/DropdownMenu.tsx
DropdownMenuのpropsの変更を行います。
これまで、Iconのメニューボタンを表示させる際には、`isIconMenu` を trueにすることで可能となっていましたが、
他コンポーネントなどとのAPIの整合性を合わせるため、`styleType = "iconButton"` へ変更します。
また、アクセシビリティの観点から、DropdownMenuで利用しているtitleも、IconButtonにてtitle属性として反映されるようになります。
> DropdownMenuのpropsの変更

- design-tokens/package.json
- package-lock.json
- ui/package.json
1. #18 のバージョンアップに合わせてdesign-tokenで使用しているstyle-dictionary-formatterもバージョンアップしました
2. serendie/uiがすでに手動で0.1.10が出ているのでバージョン番号を実態に合わせました
この変更では、design-tokenに`sd.system.dimension.breakpoint.expanded`などのbreakpointの値が含まれるようになります。 ref: #11 
マージしたらdesign-tokenをnpm publishすること
> Update design token modules

- .github/workflows/release-package.yml
main branchにdirect pushを禁止するrule setsがあるとrelease-itがうまく動かない件を解決します。
以下でも議論があるようにGitHub Actions(GITHUB_TOKEN)を使用して上記を行う方法はいくつかあります。
- botユーザーを作成しそのPATを使う
- 管理するのが大変
- pull requestを作ってマージする
- release-itが対応していない
- deploy keyを使う
https://github.com/orgs/community/discussions/25305
その中でも今回はdeploy keyを利用する方法を採用しました。以下を参考に設定します。
https://github.com/sbellone/release-workflow-example
> Use deploy key for release package workflow

- .release-it.json
モノレポだと正常にrelease-itによるリリースノート自動生成が動かないのでオフにします。
> Disable release note auto generation

- package-lock.json
- ui/package.json
- ui/src/preset.ts
- ui/src/tokens/index.ts
- ui/vite.config.ts
- Common.jsをサポートし続けるのは難しいのESMのみの出力とする
- jsx-runtimeを同梱しないようにexternalに追加
- preserveModulesを有効にしてツリーシェイキングされやすいように
#15 がマージされてから
> ビルド設定全般を見直し

- ui/src/components/IconButton.tsx
IconButtonの型定義を修正し、FigmaのデザインのIconButtonの定義と同一になるように修正しました。
ref: https://github.com/serendie/internal/issues/441
> IconButtonコンポーネントのプロパティタイプを拡張し、形状とサイズのオプションを追加

- ui/src/components/IconButton.tsx
#21 で使いされたShapeという型が参照されていなかったので削除しましたー
> 'Shape' is defined but never used.

- ui/src/components/PasswordField.stories.tsx
- ui/src/components/PasswordField.tsx
- ui/src/components/TextField.stories.tsx
- ui/src/components/TextField.tsx
ref: https://github.com/serendie/internal/issues/501
TextFieldにstartContentとendContentプロパティを追加し、
パスワード入力画面を作る際に便利なPasswordFieldコンポーネントを追加しました。
> TextFieldコンポーネントにstartContentとendContentプロパティを追加、PasswordFieldコンポーネントを追加

- src/components/Accordion/Accordion.stories.tsx
- src/components/Accordion/Accordion.tsx
- src/components/Accordion/index.ts
- src/index.ts
tree shakingが適切にできるように `import { Accordion } from "@serendie/ui/Accordion";` という形でimportできるようにexport方法を調整しました。
> Support per-module import for Accordion

- figma.config.json
ディレクトリ構造変更後、Figma Code Connectを実行した際にコンポーネントファイルが読み込まれず、Code Connectのデプロイが行われない問題を修正しました。
関連するGitHub Actionsのログ: 
https://github.com/serendie/serendie/actions/runs/14460484687/job/40552082322
> Change Figma CodeConnect include pattern for components

- package-lock.json
- package.json
- src/components/Accordion/Accordion.tsx
- src/components/Avatar/Avatar.tsx
- src/components/Badge/Badge.tsx
- src/components/Banner/Banner.tsx
- src/components/BottomNavigation/BottomNavigation.stories.tsx
- src/components/Button/Button.stories.tsx
- src/components/DashboardWidget/DashboardWidget.tsx
- src/components/Drawer/Drawer.stories.tsx
- src/components/Drawer/Drawer.tsx
- src/components/DropdownMenu/DropdownMenu.stories.tsx
- src/components/DropdownMenu/DropdownMenu.tsx
- src/components/IconButton/IconButton.stories.tsx
- src/components/List/List.stories.tsx
- src/components/Pagination/Pagination.tsx
- src/components/PasswordField/PasswordField.tsx
- src/components/Search/Search.tsx
- src/components/Select/Select.tsx
- src/components/TextField/TextField.stories.tsx
- src/components/TextField/TextField.tsx
- src/components/Toast/Toast.tsx
- src/components/TopAppBar/TopAppBar.stories.tsx
- vite.config.ts
[Serendie Symbolsのアップデート](https://github.com/serendie/serendie-symbols/releases/tag/%40serendie%2Fsymbols%401.0.0)に伴い、アイコンファイルを一括で読み込むのではなく個別にインポートすることでバンドルサイズを縮小します。
> Update Serendie Symbols

- src/assets/checkboxIndeterminate.svg
- src/components/ChoiceBox/ChoiceBox.stories.tsx
- src/components/ChoiceBox/ChoiceBox.tsx
ChoiceBoxにindeterminate状態(不確定状態)を追加しました。
ChoiceBoxコンポーネントに、チェックボックスの不確定状態を管理するためのプロパティを追加しました。
新しいSVGアイコンを追加し、状態に応じて表示を切り替えます。
Fixes https://linear.app/serendie/issue/SD-18/choiceboxinterminate
> Add indeterminate state to ChoiceBox

- .github/workflows/pkg-pr-new.yml
開発中のSDSのビルドを他の作業レポジトリから参照しやすくするために https://pkg.pr.new/ を導入します。PR毎にパッケージがビルドされ
```sh
npm i https://pkg.pr.new/serendie/serendie/@serendie/ui@f694b38
```
のようにインストールできます。 [実行例](https://github.com/serendie/serendie/actions/runs/16039582156/job/45258554791)
実行範囲は serendie/serendie に絞っているので、 symbolsなどで使いたい場合は↓で対象レポジトリを追加する必要があります。
https://github.com/organizations/serendie/settings/installations/74100690
> pkg.pr.new用の設定ファイルを追加

- README.md
- package.json
- src/client.ts
- vite.config.ts
RSC下でserendie/uiを使うと
```
Error: useEffect is not supported in Server Components
```
などのエラーが発生することがある。
利用する際にファイル冒頭に`'use client;'`と記載することでこのエラーは回避できるが、あらかじめこの記述をしたエントリポイントを用意することで簡便に利用できるよう変更しました。
以下はCCが作成したSerendie UI Next.js App Router対応 実装報告書です
本報告書は、Serendie UIライブラリをNext.js App Routerで使用する際に発生する「use client」ディレクティブ関連のエラーを解決するための実装内容と検証結果をまとめたものです。
- Serendie UIの多くのコンポーネントがArk UIのPortalやブラウザAPI（useEffect、window、document等）を使用
- Next.js App RouterのServer Componentから直接インポートするとエラーが発生
- 利用者が各ファイルで`'use client'`ディレクティブを記述する必要があり、開発体験が低下
```
Error: useEffect is not supported in Server Components
```
ライブラリ側で`@serendie/ui/client`サブエントリを提供し、利用者が`use client`ディレクティブを意識せずに使用できるようにする。
**ファイル**: `src/client.ts`
```typescript
'use client';
export * from './index';
```
```json
"./client": {
"import": …
```
> RSC向けに@serendie/ui/clientを追加

- src/components/Select/Select.tsx
異なるtypescritpのバージョン下で型チェックが通らないため、明示的にオプショナルに変更。
下位互換のため `items` を使っているが今後の方針は要検討
> selectのcollectionプロパティをoptionalに変更

- src/components/DatePicker/DatePicker.stories.tsx
- src/components/DatePicker/index.ts
- src/components/DatePicker/parseDate.ts
DatePickerの入力で使うparseDateをserendie/ui からimportして使えるようラップしました
>  parseDate を serendie/ui から export / import するように修正 

- src/components/Pagination/Pagination.tsx
Paginationのボタンが階層上入れ子になってしまい、Button要素内部にButton要素が入ってしまう問題を修正。
こちらの修正を行うことによって、ハイドレーションエラーが発生していたNext.js等のSSG/SSR環境でも問題なく利用できるようになります。
- Pagination | Ark UI
- https://ark-ui.com/docs/components/pagination
> Paginationコンポーネントの内部でbuttonが入れ子になってしまう問題を修正

- src/components/DatePicker/DatePicker.tsx
- src/components/Select/Select.tsx
- src/components/TextArea/TextArea.tsx
- src/components/TextField/TextField.tsx
DatePicker, Select, TextArea, TextFieldにて下記修正を実施：
- requiredLabelプロパティを追加
- 必須ラベルをrequiredLabelに基づくように変更。未入力時には、これまで通り必須ラベルを表示
> 必須ラベルの文言を置き換え可能にする
